plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.plugin.serialization'
    id 'org.jetbrains.kotlin.plugin.compose'
}

android {
    namespace 'hu.bme.aut.arobjectdetection.ml'
    compileSdk 36

    defaultConfig {
        applicationId "hu.bme.aut.arobjectdetection.ml"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    buildFeatures {
        compose true
    }
    packaging {
        resources {
            excludes += '/META-INF/DEPENDENCIES'
            excludes += '/META-INF/INDEX.LIST'
        }
    }
}

android.sourceSets.main.java.srcDirs += ['../third_party']

dependencies {
    implementation platform('org.jetbrains.kotlin:kotlin-bom:2.0.21')
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.7.3'
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.3"

    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.coordinatorlayout:coordinatorlayout:1.2.0'
    implementation 'androidx.lifecycle:lifecycle-common-java8:2.6.2'
    implementation 'androidx.activity:activity-ktx:1.8.2'

    implementation 'com.google.android.material:material:1.11.0'

    // MLKit
    implementation 'com.google.mlkit:object-detection:17.0.0'
    implementation 'com.google.mlkit:object-detection-custom:17.0.0'

    // ARCore
    implementation 'com.google.ar:core:1.41.0'

    // Obj - a simple Wavefront OBJ file loader
    // https://github.com/javagl/Obj
    implementation 'de.javagl:obj:0.4.0'

    // Compose
    def composeBom = platform('androidx.compose:compose-bom:2024.10.01')
    implementation composeBom
    androidTestImplementation composeBom

    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.ui:ui-graphics'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    implementation 'androidx.compose.material3:material3'
    implementation 'androidx.activity:activity-compose:1.9.3'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-compose:2.8.5'

    // Navigation 3
    implementation 'androidx.navigation3:navigation3-runtime-android:1.0.1'
    implementation 'androidx.navigation3:navigation3-ui-android:1.0.1'
    implementation 'androidx.navigationevent:navigationevent-compose-android:1.0.1'
}